openapi: 3.0.3
info:
    title: Unikraft Cloud Control Plane API
    description: This specification describes the Unikraft Cloud Control Plane API, which provides mechanisms to interact with globally provided Unikraft Cloud system.
    contact:
        name: Unikraft Support
        url: https://unikraft.com/contact
        email: support@unikraft.com
    version: v1.0.0
servers:
    - url: https://controlplane.unikraft.cloud
      description: Official Unikraft Cloud Control Plane API
paths:
    /v1/auth/check:
        post:
            tags:
                - Auth
            description: |-
                CheckAuthorization is used to check the authorization status of a request.
                It streams responses back to the client, indicating whether the signin
                request is authorized or not.
            operationId: CheckAuthorization
            requestBody:
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/CheckAuthorizationRequest'
                required: true
            responses:
                default:
                    description: default
                    content:
                        text/event-stream:
                            schema:
                                $ref: '#/components/schemas/CheckAuthorizationResponse'
    /v1/auth/signin:
        post:
            tags:
                - Auth
            description: |-
                RequestSignin initiates the sign-in process and returns an authorization
                URL.  The user should be redirected to this URL to complete the sign-in.
            operationId: RequestSignin
            requestBody:
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/RequestSigninRequest'
                required: true
            responses:
                default:
                    description: default
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/RequestSigninResponse'
components:
    schemas:
        CheckAuthorizationRequest:
            type: object
            properties:
                request_id:
                    type: string
                    description: |-
                        The request ID is a unique identifier for the request.  This is used to
                        track the request in the system and should be provided by the client.
            description: The request message for checking authorization given a request ID.
        CheckAuthorizationResponse:
            type: object
            properties:
                status:
                    enum:
                        - "success"
                        - "error"
                    type: string
                    description: The status of the response.
                    format: enum
                message:
                    type: string
                    description: An optional message providing additional information about the response.
                data:
                    allOf:
                        - $ref: '#/components/schemas/CheckAuthorizationResponseData'
                    description: The response data for this request.
                op_time_us:
                    example: 56
                    type: integer
                    description: |-
                        The operation time in microseconds.  This is the time it took to process
                        the request and generate the response.
                    format: uint64
            description: The response message for checking authorization.
        CheckAuthorizationResponseData:
            type: object
            properties:
                token:
                    type: string
                    description: The authorization token which can be used to authenticate requests.
        RequestSigninRequest:
            type: object
            properties:
                hostname:
                    example: my-machine.local
                    type: string
                    description: |-
                        The hostname is the name of the machine making the request.  This is
                        mandatory as it consitutes a unique identifier for the machine.
                os:
                    example: linux
                    type: string
                    description: The operating system of the machine making the request.
                os_version:
                    example: 5.10.0-17-amd64
                    type: string
                    description: |-
                        The version of the operating system of the machine making the request, if
                        available.

                        For Android, it's like "10", "11", "12", etc.  For iOS and macOS it's like
                        "15.6.1" or "12.4.0".  For Windows it's like "10.0.19044.1889". For FreeBSD
                        it's like "12.3-STABLE".  For Linux, this is simply the kernel version on
                        Linux, like "5.10.0-17-amd64".
                container:
                    example: false
                    type: boolean
                    description: A best-effort whether the client is running in a container.
                distro:
                    example: ubuntu
                    type: string
                    description: The OS distribution, if known.  E.g. "debian", "ubuntu", "nixos", ...
                distro_version:
                    example: 20.04
                    type: string
                    description: The OS distribution version if known.  E.g. "20.04", ...
                distro_codename:
                    example: jammy
                    type: string
                    description: TThe OS distribution codename if known.  E.g. "jammy", "bullseye", ...
                cli_version:
                    example: 1.0.0
                    type: string
                    description: |-
                        The CLI version is the version of the Unikraft CLI that is making the
                        request.
                goarch:
                    example: amd64
                    type: string
                    description: If available, the GOARCH value (of the built binary).
                goos:
                    example: linux
                    type: string
                    description: If available, the GOOS value (of the built binary)
                go_version:
                    example: 1.16.0
                    type: string
                    description: if available, the Go version binary was built with.
            description: The request message for a sign-in request.
        RequestSigninResponse:
            type: object
            properties:
                status:
                    enum:
                        - "success"
                        - "error"
                    type: string
                    description: The status of the response.
                    format: enum
                message:
                    type: string
                    description: An optional message providing additional information about the response.
                data:
                    allOf:
                        - $ref: '#/components/schemas/RequestSigninResponseData'
                    description: The response data for this request.
                op_time_us:
                    example: 87
                    type: integer
                    description: |-
                        The operation time in microseconds.  This is the time it took to process
                        the request and generate the response.
                    format: uint64
            description: The response message for a sign-in request.
        RequestSigninResponseData:
            type: object
            properties:
                authorization_url:
                    type: string
                    description: The full URL which can be used to remotely confirm the signin.
                request_id:
                    type: string
                    description: |-
                        A unique identifier for the request.  This can be used to track the
                        request in the system.
    securitySchemes:
        bearerToken:
            type: http
            scheme: bearer
tags:
    - name: Auth
