openapi: 3.0.3
info:
    title: Unikraft Cloud Control Plane API
    description: This specification describes the Unikraft Cloud Control Plane API, which provides mechanisms to interact with globally provided Unikraft Cloud system.
    contact:
        name: Unikraft Support
        url: https://unikraft.com/contact
        email: support@unikraft.com
    version: v1.0.0
servers:
    - url: https://controlplane.unikraft.cloud
      description: Official Unikraft Cloud Control Plane API
paths:
    /v1/auth/check:
        post:
            tags:
                - Auth
            description: |-
                CheckAuthorization is used to check the authorization status of a request.
                 It streams responses back to the client, indicating whether the signin
                 request is authorized or not.
            operationId: CheckAuthorization
            requestBody:
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/CheckAuthorizationRequest'
                required: true
            responses:
                "200":
                    description: OK
                    content:
                        text/event-stream:
                            schema:
                                $ref: '#/components/schemas/CheckAuthorizationResponse'
                default:
                    description: Default error response
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/Status'
    /v1/auth/signin:
        post:
            tags:
                - Auth
            description: |-
                RequestSignin initiates the sign-in process and returns an authorization
                 URL.  The user should be redirected to this URL to complete the sign-in.
            operationId: RequestSignin
            requestBody:
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/RequestSigninRequest'
                required: true
            responses:
                "200":
                    description: OK
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/RequestSigninResponse'
                default:
                    description: Default error response
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/Status'
components:
    schemas:
        CheckAuthorizationRequest:
            type: object
            properties:
                request_id:
                    type: string
                    description: |-
                        The request ID is a unique identifier for the request.  This is used to
                         track the request in the system and should be provided by the client.
            description: The request message for checking authorization given a request ID.
        CheckAuthorizationResponse:
            type: object
            properties:
                status:
                    enum:
                        - "success"
                        - "error"
                    type: string
                    description: The status of the response.
                    format: enum
                message:
                    type: string
                    description: An optional message providing additional information about the response.
                data:
                    allOf:
                        - $ref: '#/components/schemas/CheckAuthorizationResponseData'
                    description: The response data for this request.
                op_time_us:
                    type: integer
                    description: |-
                        The operation time in microseconds.  This is the time it took to process
                         the request and generate the response.
                    format: uint64
            description: The response message for checking authorization.
        CheckAuthorizationResponseData:
            type: object
            properties:
                token:
                    type: string
                    description: The authorization token which can be used to authenticate requests.
        GoogleProtobufAny:
            type: object
            properties:
                '@type':
                    type: string
                    description: The type of the serialized message.
            additionalProperties: true
            description: Contains an arbitrary serialized message along with a @type that describes the type of the serialized message.
        RequestSigninRequest:
            type: object
            properties:
                hostname:
                    type: string
                    description: |-
                        The hostname is the name of the machine making the request.  This is
                         mandatory as it consitutes a unique identifier for the machine.
                os:
                    type: string
                    description: The operating system of the machine making the request.
                os_version:
                    type: string
                    description: |-
                        The version of the operating system of the machine making the request, if
                         available.

                         For Android, it's like "10", "11", "12", etc.  For iOS and macOS it's like
                         "15.6.1" or "12.4.0".  For Windows it's like "10.0.19044.1889". For FreeBSD
                         it's like "12.3-STABLE".  For Linux, this is simply the kernel version on
                         Linux, like "5.10.0-17-amd64".
                container:
                    type: boolean
                    description: A best-effort whether the client is running in a container.
                distro:
                    type: string
                    description: The OS distribution, if known.  E.g. "debian", "ubuntu", "nixos", ...
                distro_version:
                    type: string
                    description: The OS distribution version if known.  E.g. "20.04", ...
                distro_codename:
                    type: string
                    description: THe OS distribution codename if known.  E.g. "jammy", "bullseye", ...
                cli_version:
                    type: string
                    description: |-
                        The CLI version is the version of the Unikraft CLI that is making the
                         request.
                goarch:
                    type: string
                    description: If available, the GOARCH value (of the built binary).
                goos:
                    type: string
                    description: If available, the GOOS value (of the built binary)
                go_version:
                    type: string
                    description: if available, the Go version binary was built with.
            description: The request message for a sign-in request.
        RequestSigninResponse:
            type: object
            properties:
                status:
                    enum:
                        - "success"
                        - "error"
                    type: string
                    description: The status of the response.
                    format: enum
                message:
                    type: string
                    description: An optional message providing additional information about the response.
                data:
                    allOf:
                        - $ref: '#/components/schemas/RequestSigninResponseData'
                    description: The response data for this request.
                op_time_us:
                    type: integer
                    description: |-
                        The operation time in microseconds.  This is the time it took to process
                         the request and generate the response.
                    format: uint64
            description: The response message for a sign-in request.
        RequestSigninResponseData:
            type: object
            properties:
                authorization_url:
                    type: string
                    description: The full URL which can be used to remotely confirm the signin.
                request_id:
                    type: string
                    description: |-
                        A unique identifier for the request.  This can be used to track the
                         request in the system.
        Status:
            type: object
            properties:
                code:
                    type: integer
                    description: The status code, which should be an enum value of [google.rpc.Code][google.rpc.Code].
                    format: int32
                message:
                    type: string
                    description: A developer-facing error message, which should be in English. Any user-facing error message should be localized and sent in the [google.rpc.Status.details][google.rpc.Status.details] field, or localized by the client.
                details:
                    type: array
                    items:
                        $ref: '#/components/schemas/GoogleProtobufAny'
                    description: A list of messages that carry the error details.  There is a common set of message types for APIs to use.
            description: 'The `Status` type defines a logical error model that is suitable for different programming environments, including REST APIs and RPC APIs. It is used by [gRPC](https://github.com/grpc). Each `Status` message contains three pieces of data: error code, error message, and error details. You can find out more about this error model and how to work with it in the [API Design Guide](https://cloud.google.com/apis/design/errors).'
    securitySchemes:
        bearerToken:
            type: http
            scheme: bearer
tags:
    - name: Auth
